#!/bin/sh

if [ $# -ne 2 ]
then
    echo "USAGE: $0 <partial assembly> <executable file>"
    echo "Given our compiler output, produces an object file named shitty.o"
    exit 1
fi

srcfile="$1"
outfile="$2"
tmpfile="/tmp/shitty.s"

cat >"$tmpfile" <<EOHEADER
	.globl main
main:
EOHEADER

cat "$srcfile" >>"$tmpfile"

cat >>"$tmpfile" <<EOFOOTER
	movl %eax, %edi
	call putint
	movl \$0, %eax
	ret
EOFOOTER

gcc -o "$outfile" "$tmpfile" "`dirname $0`/putint.s"
#rm "$tmpfile"

true
